import type { Metadata } from 'next';
import { K2D } from 'next/font/google';
import './globals.css';

import { QueryProvider } from '@/providers/QueryProvider';

const font = K2D({ subsets: ['latin'], weight: '400' });

export const metadata: Metadata = {
  title: 'Spells',
  description: 'Generated by create next app'
};

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={font.className}>
        <QueryProvider>{children}</QueryProvider>
      </body>
    </html>
  );
}
